### PR TITLE
Refactored third-party modules import, changed build script and fixed few minor bugs

### PR DESCRIPTION
**Pull request by SuperPaintman**
Good afternoon!

I changed the build system a little:
  * Removed third-party modules' files and moved them to the Node modules (`vivus` and `dom-to-image`)
  * Replaced `tsc` build script with Webpack (I did it for better `webview` support)

Also I fixed few bugs (mistakes):
  * `innerText` -> `textContent`
  * `classList` -> `className` - because you assigned string to the `classList`

### CODE REVIEW

**Comment by octref** [comment]
If it's possible to not have the build system I'd like to avoid it and all the dependencies. I like it much better that I can write and reload the JS on the fly instead of having build/watch systems. What do you mean by `better webview support`?

The other two fixes are good -- thanks!

**Comment by octref** [comment]
> You can do it with Webpack too: webpack --watch. And TS is already a sorta build system :)

I'm using TS for building the code running as extension, not the webview code.
Also with webpack the sourcemap might cause problem for debugging the webview code.

> t bundles all "browser" dependencies, auto injects script into HTML template, adds support for other "Web" features like a import no-TS/JS files (CSS for example).

Which I don't need. We are not building a whole app here.
Would you mind opening another PR for just the `innerText` and `classList` changes?

**Comment by SuperPaintman** [comment]
@octref https://github.com/octref/polacode/pull/36

**Comment by ahmadawais** [comment]
@octref Can you share where can I find API ref for webview in VSCode?

**Comment by SuperPaintman** [comment]
@octref see https://github.com/octref/polacode/pull/37

**Comment by octref** [comment]
@ahmadawais Sadly only https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample and https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands#_working-with-the-html-preview.

Currently @mjbvz is working on a new version of the API and he'll also add a dedicated doc page for developing webview extensions in our website.

**Comment by ahmadawais** [comment]
@octref thanks for that. I was not able to find much on it and these two links is what I ended up with on my own. Looking forward @mjbvz!

**Pull request closed without merging**
